version: '3'

services:
  api:
    container_name: api
    build:
      context: "./backend/api"  
      dockerfile: Dockerfile
      args:    
        - http_proxy
        - https_proxy
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
      